name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Install dependencies
        run: pnpm install
      - name: Lint
        run: pnpm exec eslint .
      - name: Unit & Integration Tests
        run: pnpm test
      - name: Build Web
        run: pnpm --filter web build

  e2e:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Install dependencies
        run: pnpm install
      - name: Run E2E Tests
        run: pnpm test # replace with actual e2e runner

  deploy:
    runs-on: ubuntu-latest
    needs: e2e
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Vercel (placeholder)
        run: echo "Deploy to Vercel via VERCEL_TOKEN"
      - name: Deploy Supabase Functions (placeholder)
        run: echo "Deploy via Supabase CLI"
